-dontwarn org.slf4j.impl.StaticLoggerBinder
-dontwarn org.slf4j.**
-keep class kotlinx.serialization.** { *; }
-keepclassmembers class kotlinx.serialization.** { *; }
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
